#!/usr/bin/env python3
#
#  __main__.py
"""
wxPython GUI for saving icons to files.
"""
#
#  Copyright (c) 2019-2021 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
# generated by wxGlade 0.9.0 on Mon Feb 25 13:14:25 2019
#

# 3rd party
import wx  # type: ignore

# this package
from wxIconSaver import BitmapSaverFrame

__all__ = ["BitmapSaver", "main"]


class BitmapSaver(wx.App):
	"""
	The main application class.
	"""

	def OnInit(self):  # noqa: D102
		self.frame = BitmapSaverFrame(None, wx.ID_ANY, '')
		self.SetTopWindow(self.frame)
		self.frame.Show()
		return True


# end of class BitmapSaver


def main():  # noqa: D103
	app = BitmapSaver(0)
	app.MainLoop()


if __name__ == "__main__":
	main()
